# Generated by Django 5.1.2 on 2025-09-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=240)),
                ("url", models.URLField()),
                ("published_on", models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("issuer", models.CharField(max_length=160)),
                ("certificate_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experience_type",
                    models.CharField(
                        choices=[
                            ("internship", "Internship"),
                            ("achievement", "Achievement/Award"),
                            ("leadership", "Leadership/Workshop"),
                        ],
                        default="internship",
                        max_length=20,
                    ),
                ),
                ("organization", models.CharField(max_length=160)),
                ("role", models.CharField(max_length=160)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("start_date", models.CharField(blank=True, max_length=60)),
                ("end_date", models.CharField(blank=True, max_length=60)),
                ("bullets", models.TextField(blank=True, help_text="One per line")),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("tech_stack", models.CharField(blank=True, max_length=240)),
                ("description", models.TextField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("featured", models.BooleanField(default=False)),
                ("date_range", models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("title", models.CharField(blank=True, max_length=160)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("summary", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="about_photos/"),
                ),
                (
                    "roles_open_for",
                    models.CharField(
                        blank=True, help_text="Comma separated roles", max_length=240
                    ),
                ),
                (
                    "social_links",
                    models.ManyToManyField(blank=True, to="portfolio.sociallink"),
                ),
            ],
        ),
    ]
