# Generated by Django 5.1.2 on 2025-09-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Academic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=240)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("date_range", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True, help_text="One per line")),
            ],
        ),
    ]
