# Generated by Django 5.1.2 on 2025-09-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_academic"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="role",
            field=models.CharField(
                blank=True,
                help_text="Primary role this project maps to (e.g., backend, genai, mlds, ux)",
                max_length=60,
            ),
        ),
    ]
