# Generated by Django 5.1.2 on 2025-09-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_project_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="tech_stack",
            field=models.CharField(
                blank=True,
                help_text="Comma separated technologies used",
                max_length=512,
            ),
        ),
    ]
